import { Router } from 'express';
import { validate } from '../../shared/middleware/validate.js';
import { authenticate } from '../auth/public.js';
import { collaborationController } from './collaboration.controller.js';
import { addActivitySchema, addFileSchema, agreementActionSchema, collaborationIdSchema, collaborationListSchema, lockAgreementSchema, taskSchema, updateTermsSchema } from './collaboration.schema.js';
export const collaborationRouter = Router();
collaborationRouter.use(authenticate);
collaborationRouter.get('/', validate(collaborationListSchema), collaborationController.list);
collaborationRouter.get('/:id', validate(collaborationIdSchema), collaborationController.get);
collaborationRouter.patch('/:id/terms', validate(updateTermsSchema), collaborationController.updateTerms);
collaborationRouter.post('/:id/agreement/lock', validate(lockAgreementSchema), collaborationController.lockAgreement);
collaborationRouter.post('/:id/agreement/action', validate(agreementActionSchema), collaborationController.agreementAction);
collaborationRouter.post('/:id/tasks/:taskId/toggle', validate(taskSchema), collaborationController.toggleTask);
collaborationRouter.post('/:id/files', validate(addFileSchema), collaborationController.addFile);
collaborationRouter.post('/:id/activity', validate(addActivitySchema), collaborationController.addActivity);
