export const toPayment = (payment) => ({
  id: payment.id,
  collaborationId: payment.collaborationId,
  parentId: payment.parentId,
  type: payment.type,
  paymentType: payment.compensationType,
  status: payment.status,
  amount: Number(payment.amount),
  cashAmount: Number(payment.cashAmount || 0),
  barterEstimatedValue: payment.barterEstimatedValue === null ? null : Number(payment.barterEstimatedValue),
  commissionRate: Number(payment.commissionRate || 0),
  commissionAmount: Number(payment.commissionAmount || 0),
  creatorAmount: Number(payment.creatorAmount || 0),
  platformFee: Number(payment.platformFee),
  currency: payment.currency,
  provider: payment.provider,
  providerRef: payment.providerRef,
  failureReason: payment.failureReason,
  processedAt: payment.processedAt,
  fundedAt: payment.fundedAt,
  releasedAt: payment.releasedAt,
  refundedAt: payment.refundedAt,
  createdAt: payment.createdAt,
});

export const toMethod = (method) => ({
  id: method.id,
  provider: method.provider,
  brand: method.brand,
  last4: method.last4,
  expMonth: method.expMonth,
  expYear: method.expYear,
  isDefault: method.isDefault,
  createdAt: method.createdAt,
});
