import { Router } from 'express';
import { validate } from '../../shared/middleware/validate.js';
import { authenticate } from '../auth/public.js';
import { paymentController } from './payment.controller.js';
import { payoutAccountController } from './payout-account.controller.js';
import { addMethodSchema, earningsQuerySchema, fundingIntentSchema, methodIdSchema, paymentIdSchema, paymentListSchema, payoutAccountSchema, payoutSchema, qpayCallbackSchema, refundSchema, walletFundingSchema, walletSummarySchema, walletTopUpSchema, webhookSchema } from './payment.schema.js';
export const collaborationPaymentRouter = Router();
collaborationPaymentRouter.post('/:id/payments/funding-intent', authenticate, validate(fundingIntentSchema), paymentController.createFundingIntent);
collaborationPaymentRouter.get('/:id/payments/summary', authenticate, validate(paymentIdSchema), paymentController.collaborationPaymentSummary);
collaborationPaymentRouter.post('/:id/payments/fund', authenticate, validate(walletFundingSchema), paymentController.fundFromWallet);
export const paymentRouter = Router();
paymentRouter.post('/webhooks/mock', validate(webhookSchema), paymentController.webhook);
paymentRouter.post('/webhooks/qpay', validate(qpayCallbackSchema), paymentController.qpayWebhook);
paymentRouter.post('/webhooks/stripe', paymentController.stripeWebhook);
paymentRouter.use(authenticate);
paymentRouter.get('/wallet', validate(walletSummarySchema), paymentController.wallet);
paymentRouter.post('/wallet/top-ups', validate(walletTopUpSchema), paymentController.createTopUp);
paymentRouter.get('/transactions', validate(paymentListSchema), paymentController.list);
paymentRouter.get('/methods', paymentController.methods);
paymentRouter.get('/payout-accounts', payoutAccountController.list);
paymentRouter.post('/payout-accounts', validate(payoutAccountSchema), payoutAccountController.create);
paymentRouter.delete('/payout-accounts/:id', validate(methodIdSchema), payoutAccountController.remove);
paymentRouter.post('/methods', validate(addMethodSchema), paymentController.addMethod);
paymentRouter.delete('/methods/:id', validate(methodIdSchema), paymentController.removeMethod);
paymentRouter.post('/:id/mock-confirm', validate(paymentIdSchema), paymentController.mockConfirm);
paymentRouter.post('/:id/refunds', validate(refundSchema), paymentController.refund);
paymentRouter.post('/:id/payouts', validate(payoutSchema), paymentController.payout);
paymentRouter.get('/earnings/summary', validate(earningsQuerySchema), paymentController.earningsSummary);
paymentRouter.get('/earnings/export.csv', validate(earningsQuerySchema), paymentController.earningsExport);
