import { useState } from 'react'
import { ArrowLeft, Bell, Check, MoreHorizontal, Plus, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { BrandLogo } from '../components/BrandLogo'
import { Avatar, Badge, Button, Card, Checkbox, Dialog, Drawer, Dropdown, EmptyState, Input, Select, Skeleton, Spinner, Switch, Tabs, Textarea, Tooltip, useToast } from '../components/ui'

function Section({ number, title, copy, children }) { return <section className="border-t border-[var(--border)] py-12 md:py-16"><div className="grid gap-8 lg:grid-cols-[16rem_1fr]"><div><p className="eyebrow text-pink">{number}</p><h2 className="heading-md mt-3">{title}</h2><p className="body-muted mt-3 text-sm">{copy}</p></div><div>{children}</div></div></section> }

export default function DesignSystemPage() {
  const [checked, setChecked] = useState(true); const [enabled, setEnabled] = useState(true); const [dialog, setDialog] = useState(false); const [drawer, setDrawer] = useState(false); const [tab, setTab] = useState('creator'); const [dropdown, setDropdown] = useState('recent'); const [theme, setTheme] = useState('dark'); const { toast } = useToast()
  return <main data-theme={theme} className="min-h-screen bg-[var(--background)] text-[var(--foreground)]"><header className="border-b border-[var(--border)] px-5 py-5 md:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between"><div className="flex items-center gap-5"><Link to="/" aria-label="Back home"><ArrowLeft size={18} /></Link><BrandLogo /><Badge variant="outline">Design system</Badge></div><Button size="sm" variant="outline" onClick={() => setTheme((value) => value === 'dark' ? 'light' : 'dark')}>Toggle theme</Button></div></header>
    <div className="mx-auto max-w-7xl px-5 md:px-10"><div className="py-16 md:py-24"><p className="eyebrow text-[var(--subtle)]">Foundation · v1.0</p><h1 className="display-xl mt-5 uppercase">DESIGNED FOR<br/><span className="editorial text-pink">good influence.</span></h1><p className="body-muted mt-7 max-w-2xl">A tactile, editorial system for a creator marketplace—high contrast foundations, generous rhythm, warm neutrals, and confident pink and mint signals.</p></div>
      <Section number="01" title="Color & theme" copy="Semantic tokens adapt across light and dark surfaces."><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Ink','#0D0D0D','bg-ink text-white'],['Canvas','#F7F7F2','bg-canvas text-ink'],['Pink','#FF76BD','bg-pink text-ink'],['Mint','#BBF7D0','bg-mint text-ink']].map(([name, hex, style]) => <div key={name} className={`flex min-h-40 flex-col justify-end rounded-2xl p-4 ${style}`}><strong>{name}</strong><span className="mt-1 text-xs opacity-60">{hex}</span></div>)}</div></Section>
      <Section number="02" title="Typography" copy="Editorial display type meets crisp interface typography."><div className="space-y-8"><div><span className="eyebrow text-[var(--subtle)]">Display XL</span><p className="display-xl mt-2">Culture <span className="editorial text-pink">moves.</span></p></div><div><span className="eyebrow text-[var(--subtle)]">Heading large</span><p className="heading-lg mt-2">The right voice, at the right time.</p></div><div><span className="eyebrow text-[var(--subtle)]">Body</span><p className="body-muted mt-2 max-w-xl">Clear, thoughtful copy creates confidence around every collaboration.</p></div></div></Section>
      <Section number="03" title="Actions & status" copy="Variants cover hierarchy, intent and feedback."><div className="space-y-7"><div className="flex flex-wrap gap-3"><Button>Primary</Button><Button variant="pink">Pink action</Button><Button variant="mint">Mint action</Button><Button variant="secondary">Secondary</Button><Button variant="outline">Outline</Button><Button variant="ghost">Ghost</Button><Button variant="danger">Danger</Button><Button loading>Loading</Button></div><div className="flex flex-wrap gap-2"><Badge>Neutral</Badge><Badge variant="pink">Creator</Badge><Badge variant="mint"><Check size={11} /> Verified</Badge><Badge variant="dark">Featured</Badge><Badge variant="outline">Draft</Badge></div></div></Section>
      <Section number="04" title="Forms" copy="Accessible input states and consistent form rhythm."><div className="form-grid"><Input label="Channel name" placeholder="Nomad Frames" help="Shown publicly on your channel." /><Input label="Username" placeholder="@nomadframes" error="This username is already in use." /><Select label="Primary niche" options={['Fashion','Travel','Technology']} /><Input label="Disabled" value="Unavailable field" disabled readOnly /><Textarea className="form-span-2" label="Bio" placeholder="Describe your point of view..." /><Card><Checkbox label="Email notifications" description="Get updates about new campaign matches." checked={checked} onChange={(event) => setChecked(event.target.checked)} /></Card><Card><Switch label="Public rates" description="Show starting rates on profile." checked={enabled} onChange={(event) => setEnabled(event.target.checked)} /></Card></div></Section>
      <Section number="05" title="Identity & surfaces" copy="Profiles and content use the same soft geometry."><div className="space-y-6"><div className="flex items-end gap-4"><Avatar size="sm" fallback="NB" /><Avatar fallback="AK" status="online" /><Avatar size="lg" fallback="VY" /><Avatar size="xl" src="https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=300&q=80" alt="Creator" /></div><div className="grid gap-4 md:grid-cols-3">{['Creator discovery','Clear collaboration','Measurable work'].map((title, index) => <Card key={title} interactive><span className="grid size-10 place-items-center rounded-full bg-pink-soft"><Sparkles size={16} /></span><h3 className="heading-md mt-10">{title}</h3><p className="body-muted mt-3 text-sm">Premium surfaces stay calm, useful and unmistakably on-brand.</p><span className="mt-6 block text-xs text-[var(--subtle)]">0{index + 1}</span></Card>)}</div></div></Section>
      <Section number="06" title="Overlays & navigation" copy="Focused layers preserve context with subtle motion."><div className="flex flex-wrap gap-3"><Button variant="outline" onClick={() => setDialog(true)}>Open dialog</Button><Button variant="outline" onClick={() => setDrawer(true)}>Open drawer</Button><Dropdown label="Sort by" items={[{label:'Most recent',value:'recent'},{label:'Highest reach',value:'reach'}]} value={dropdown} onChange={setDropdown} /><Tooltip content="Notifications are up to date"><button aria-label="Show notification status" className="grid size-11 place-items-center rounded-full border border-[var(--border)]"><Bell size={17} /></button></Tooltip></div><div className="mt-8"><Tabs value={tab} onChange={setTab} tabs={[{label:'Creator',value:'creator',content:<Card>Creator channel content area</Card>},{label:'Business',value:'business',content:<Card>Business channel content area</Card>}]} /></div><Dialog open={dialog} onClose={() => setDialog(false)} title="Invite collaborator" description="This is a reusable animated dialog."><Input label="Email address" placeholder="collaborator@studio.com" /><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={() => setDialog(false)}>Cancel</Button><Button variant="pink" onClick={() => { setDialog(false); toast('Mock invitation sent.', { type: 'success' }) }}>Send invite</Button></div></Dialog><Drawer open={drawer} onClose={() => setDrawer(false)} title="Notification settings"><div className="space-y-5"><Switch label="Campaign matches" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} /><Switch label="Creator messages" checked={checked} onChange={(event) => setChecked(event.target.checked)} /></div></Drawer></Section>
      <Section number="07" title="Loading & empty" copy="Quiet states make system status obvious without visual noise."><div className="grid gap-5 md:grid-cols-2"><Card><div className="flex items-center gap-3"><Skeleton className="size-12 rounded-full" /><div className="flex-1"><Skeleton className="h-4 w-2/3" /><Skeleton className="mt-2 h-3 w-1/2" /></div></div><Skeleton className="mt-5 h-32 w-full" /><div className="mt-5 flex items-center justify-between"><Spinner /><Button size="sm" disabled><Plus size={14} /> Add work</Button></div></Card><EmptyState title="No portfolio work yet" description="Add your first project to show brands what you do best." onAction={() => toast('Mock create action.', { type: 'info' })} /></div></Section>
      <footer className="flex items-center justify-between border-t border-[var(--border)] py-8 text-xs text-[var(--subtle)]"><span>VYRA Design System</span><MoreHorizontal size={18} /></footer>
    </div>
  </main>
}
