import { useState } from 'react'
import { Building2, LockKeyhole, Sparkles } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { OnboardingLayout, ReviewList, StepActions, StepHeading } from '../../components/onboarding/OnboardingLayout'
import { Card, Checkbox, FileUpload, Input, Select, Textarea, useToast } from '../../components/ui'
import { useMarketplace } from '../../context/marketplace-context'
import { useBusiness } from '../../hooks/useBusiness'
import { useOnboardingDraft } from '../../hooks/useOnboardingDraft'
import { normalizeUsername } from '../../utils/onboarding'
import { mediaApi } from '../../api/media.api'

const steps = ['Business identity', 'Business details', 'Campaign interest', 'Review & finish']
const initial = { organization: '', username: '', description: '', industry: '', website: '', companySize: '', location: '', targetNiche: '', campaignGoal: '', monthlyBudget: '', consent: false }

export default function BusinessOnboardingPage() {
  const { data, setData, current, setCurrent, maxStep, setMaxStep, clearDraft } = useOnboardingDraft('business', initial, steps.length); const [errors, setErrors] = useState({}); const [finishing, setFinishing] = useState(false); const [mediaFiles, setMediaFiles] = useState({ logo: null, cover: null }); const { updateAccount } = useMarketplace(); const businessProfile = useBusiness(); const navigate = useNavigate(); const { toast } = useToast()
  const set = (name) => (event) => setData((value) => ({ ...value, [name]: event?.target?.type === 'checkbox' ? event.target.checked : event?.target?.value ?? event }))
  const validate = () => { const next = {}; if (current === 0) { if (!data.organization.trim()) next.organization = 'Organization name is required'; if (!normalizeUsername(data.username)) next.username = 'Choose a valid username' } if (current === 1 && !data.industry) next.industry = 'Select your industry'; if (current === 2) { if (!data.targetNiche) next.targetNiche = 'Select a target niche'; if (!data.campaignGoal.trim()) next.campaignGoal = 'Tell us your main campaign goal' } setErrors(next); return !Object.keys(next).length }
  const next = () => { if (!validate()) return; const destination = Math.min(current + 1, steps.length - 1); setMaxStep((value) => Math.max(value, destination)); setCurrent(destination); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const finish = async () => { if (!data.consent) { toast('Confirm the business information first.', { type: 'error' }); return } setFinishing(true); try { const [logoUpload, coverUpload] = await Promise.all([mediaFiles.logo ? mediaApi.upload(mediaFiles.logo, 'LOGO') : null, mediaFiles.cover ? mediaApi.upload(mediaFiles.cover, 'COVER') : null]); const payload = { organization: data.organization.trim(), username: normalizeUsername(data.username).replace(/^@/, ''), description: data.description, industry: data.industry, website: data.website, companySize: data.companySize, location: data.location, targetNiche: data.targetNiche, campaignGoal: data.campaignGoal, monthlyBudget: data.monthlyBudget, logoMediaId: logoUpload?.asset?.id, coverMediaId: coverUpload?.asset?.id }; const result = await businessProfile.createProfile(payload); updateAccount('business', result.profile); clearDraft(); toast('Business Channel created and connected to My Account.', { type: 'success' }); navigate('/business/dashboard') } catch (error) { setErrors(error.details || {}); toast(error.message, { type: 'error' }) } finally { setFinishing(false) } }
  const goToStep = (index) => { if (index > maxStep) return; setErrors({}); setCurrent(index); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  return <OnboardingLayout type="Business" steps={steps} current={current} maxStep={maxStep} onBack={() => setCurrent((value) => Math.max(0, value - 1))} onStepChange={goToStep}>
    {current === 0 && <><StepHeading title="DEFINE YOUR" script="business." copy="Create the identity creators will see when they consider your campaigns. Your draft is restored automatically after refresh." /><div className="form-grid"><Input label="Organization name" value={data.organization} onChange={set('organization')} placeholder="e.g. Northstar Studio" error={errors.organization} /><Input label="Username" value={data.username} onChange={(event) => { set('username')(event); setErrors((value) => ({ ...value, username: '' })) }} onBlur={() => setData((value) => ({ ...value, username: normalizeUsername(value.username) }))} placeholder="@northstar" error={errors.username} help="Checked against existing and locally created channels." /><FileUpload label="Logo" compact value={data.logo} onChange={(files) => { const file = files[0] || null; setMediaFiles((value) => ({ ...value, logo: file })); setData((value) => ({ ...value, logo: file?.name || '' })) }} /><FileUpload label="Cover image" compact value={data.cover} onChange={(files) => { const file = files[0] || null; setMediaFiles((value) => ({ ...value, cover: file })); setData((value) => ({ ...value, cover: file?.name || '' })) }} /><Textarea className="form-span-2" label="Description" value={data.description} onChange={set('description')} placeholder="What does your organization make, value and want to change?" maxLength={320} help={`${data.description.length}/320 characters`} /></div><StepActions current={current} onNext={next} /></>}
    {current === 1 && <><StepHeading title="ADD THE" script="details." copy="A few essentials help creators understand the scale and context of your organization." /><div className="form-grid"><Select label="Industry" value={data.industry} onChange={set('industry')} options={['Fashion & apparel', 'Beauty & wellness', 'Food & beverage', 'Travel & hospitality', 'Technology', 'Entertainment', 'Agency', 'Nonprofit', 'Other']} error={errors.industry} /><Input label="Website" type="url" value={data.website} onChange={set('website')} placeholder="https://company.com" /><Select label="Company size" value={data.companySize} onChange={set('companySize')} options={['1–10', '11–50', '51–200', '201–500', '501–1,000', '1,000+']} /><Input label="Location" value={data.location} onChange={set('location')} placeholder="Ulaanbaatar, Mongolia" /></div><StepActions current={current} onBack={() => setCurrent(0)} onNext={next} /></>}
    {current === 2 && <><StepHeading title="SIGNAL YOUR" script="ambition." copy="This shapes future creator recommendations. It does not create or publish a campaign." /><div className="form-grid"><Select label="Target niche" value={data.targetNiche} onChange={set('targetNiche')} options={['Fashion', 'Beauty', 'Food', 'Travel', 'Gaming', 'Technology', 'Sport', 'Lifestyle', 'Multi-niche']} error={errors.targetNiche} /><Select label="Expected monthly budget" value={data.monthlyBudget} onChange={set('monthlyBudget')} options={['Under ₮5M', '₮5M–₮15M', '₮15M–₮40M', '₮40M–₮100M', '₮100M+']} /><Textarea className="form-span-2" label="Campaign goal" value={data.campaignGoal} onChange={set('campaignGoal')} placeholder="e.g. Launch a new product with trusted local creators and build high-quality UGC." error={errors.campaignGoal} /></div><Card className="mt-6 flex gap-4 bg-mint-soft/50"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-mint"><Building2 size={18} /></span><div><p className="text-sm font-bold">This is preference data only</p><p className="ui-help">No campaign, spend or commitment is created. It simply prepares a better future setup experience.</p></div></Card><StepActions current={current} onBack={() => setCurrent(1)} onNext={next} /></>}
    {current === 3 && <><StepHeading title="READY FOR" script="collaboration." copy="Review your public business profile before creating the channel." /><div className="mb-6 flex items-center gap-3 rounded-2xl bg-pink-soft p-4 text-sm text-[#7d1f50]"><Sparkles size={18} /><strong>Your business channel is ready for a final look.</strong></div><ReviewList items={[["Organization", data.organization], ["Username", data.username], ["Industry", data.industry], ["Website", data.website], ["Company size", data.companySize], ["Location", data.location], ["Target niche", data.targetNiche], ["Campaign goal", data.campaignGoal], ["Monthly budget", data.monthlyBudget]]} /><Card className="mt-5"><Checkbox label="I confirm this business information is accurate" description="You can edit these fields later from My Account." checked={data.consent} onChange={set('consent')} /></Card><div className="mt-4 flex items-center gap-2 text-xs text-[var(--subtle)]"><LockKeyhole size={14} /> Profile data is sent securely to your account.</div><StepActions current={current} onBack={() => setCurrent(2)} onNext={finish} finish loading={finishing} /></>}
  </OnboardingLayout>
}
