import { useState } from 'react'
import { CheckCircle2, CircleAlert, LockKeyhole, Sparkles } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { OnboardingLayout, ReviewList, StepActions, StepHeading } from '../../components/onboarding/OnboardingLayout'
import { Badge, Card, Checkbox, FileUpload, Input, Select, Switch, Textarea, useToast } from '../../components/ui'
import { useMarketplace } from '../../context/marketplace-context'
import { useCreator } from '../../hooks/useCreator'
import { useOnboardingDraft } from '../../hooks/useOnboardingDraft'
import { normalizeUsername } from '../../utils/onboarding'
import { mediaApi } from '../../api/media.api'

const steps = ['Channel identity', 'Creator details', 'Social accounts', 'Portfolio', 'Rates & availability', 'Review & finish']
const initial = { channelName: '', username: '', bio: '', niche: '', audience: '', format: '', location: '', language: '', instagram: '', facebook: '', manualLink: '', workTitle: '', workCategory: '', workDescription: '', postRate: '', storyRate: '', reelRate: '', publicRates: true, availability: '', consent: false }

export default function CreatorOnboardingPage() {
  const { data, setData, current, setCurrent, maxStep, setMaxStep, clearDraft } = useOnboardingDraft('creator', initial, steps.length); const [errors, setErrors] = useState({}); const [finishing, setFinishing] = useState(false); const [mediaFiles, setMediaFiles] = useState({ avatar: null, cover: null, sample: null }); const { updateAccount } = useMarketplace(); const creatorProfile = useCreator(); const { toast } = useToast(); const navigate = useNavigate()
  const set = (name) => (event) => setData((value) => ({ ...value, [name]: event?.target?.type === 'checkbox' ? event.target.checked : event?.target?.value ?? event }))
  const validate = () => { const next = {}; if (current === 0) { if (!data.channelName.trim()) next.channelName = 'Channel name is required'; if (!normalizeUsername(data.username)) next.username = 'Choose a valid username' } if (current === 1 && !data.niche) next.niche = 'Select your primary niche'; if (current === 2 && !data.instagram && !data.facebook && !data.manualLink) next.social = 'Add at least one social account or link'; if (current === 3) { if (!mediaFiles.sample) next.sample = 'Choose a sample image or video again after a refresh'; if (!data.workTitle.trim()) next.workTitle = 'Give your sample work a title' } if (current === 4 && !data.availability) next.availability = 'Select your availability'; setErrors(next); return !Object.keys(next).length }
  const next = () => { if (!validate()) return; const destination = Math.min(current + 1, steps.length - 1); setMaxStep((value) => Math.max(value, destination)); setCurrent(destination); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const finish = async () => { if (!data.consent) { toast('Confirm the profile information first.', { type: 'error' }); return } setFinishing(true); try { const [avatarUpload, coverUpload, sampleUpload] = await Promise.all([mediaFiles.avatar ? mediaApi.upload(mediaFiles.avatar, 'AVATAR') : null, mediaFiles.cover ? mediaApi.upload(mediaFiles.cover, 'COVER') : null, mediaFiles.sample ? mediaApi.upload(mediaFiles.sample, 'PORTFOLIO') : null]); const payload = { channelName: data.channelName.trim(), username: normalizeUsername(data.username).replace(/^@/, ''), bio: data.bio, niche: data.niche, audience: data.audience, format: data.format, location: data.location, language: data.language, instagram: data.instagram, facebook: data.facebook, manualLink: data.manualLink, postRate: data.postRate, storyRate: data.storyRate, reelRate: data.reelRate, publicRates: data.publicRates, availability: data.availability, workTitle: data.workTitle, workCategory: data.workCategory, workDescription: data.workDescription, avatarMediaId: avatarUpload?.asset?.id, coverMediaId: coverUpload?.asset?.id, sampleMediaId: sampleUpload?.asset?.id }; const result = await creatorProfile.createProfile(payload); updateAccount('creator', result.profile); clearDraft(); toast('Creator Channel created and connected to My Account.', { type: 'success' }); navigate('/creator/dashboard') } catch (error) { setErrors(error.details || {}); toast(error.message, { type: 'error' }) } finally { setFinishing(false) } }
  const goToStep = (index) => { if (index > maxStep) return; setErrors({}); setCurrent(index); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  return <OnboardingLayout type="Creator" steps={steps} current={current} maxStep={maxStep} onBack={() => setCurrent((value) => Math.max(0, value - 1))} onStepChange={goToStep}>
    {current === 0 && <><StepHeading title="NAME YOUR" script="channel." copy="Create a clear identity that brands and collaborators will recognize. Your draft is restored automatically after refresh." /><div className="form-grid"><Input label="Channel name" value={data.channelName} onChange={set('channelName')} placeholder="e.g. Nomad Frames" error={errors.channelName} /><Input label="Username" value={data.username} onChange={(event) => { set('username')(event); setErrors((value) => ({ ...value, username: '' })) }} onBlur={() => setData((value) => ({ ...value, username: normalizeUsername(value.username) }))} placeholder="@nomadframes" error={errors.username} help="Availability is confirmed securely when you finish." /><FileUpload label="Avatar" compact value={data.avatar} onChange={(files) => { const file = files[0] || null; setMediaFiles((value) => ({ ...value, avatar: file })); setData((value) => ({ ...value, avatar: file?.name || '' })) }} /><FileUpload label="Cover image" compact value={data.cover} onChange={(files) => { const file = files[0] || null; setMediaFiles((value) => ({ ...value, cover: file })); setData((value) => ({ ...value, cover: file?.name || '' })) }} /><Textarea className="form-span-2" label="Bio" value={data.bio} onChange={set('bio')} placeholder="Tell brands what makes your voice distinctive." maxLength={240} help={`${data.bio.length}/240 characters`} /></div><StepActions current={current} onNext={next} /></>}
    {current === 1 && <><StepHeading title="SHAPE YOUR" script="profile." copy="Help the marketplace understand your point of view and who follows your work." /><div className="form-grid"><Select label="Primary niche" value={data.niche} onChange={set('niche')} options={['Fashion', 'Beauty', 'Food', 'Travel', 'Gaming', 'Technology', 'Sport', 'Lifestyle']} error={errors.niche} /><Select label="Content format" value={data.format} onChange={set('format')} options={['Short-form video', 'Long-form video', 'Photography', 'Live stream', 'Editorial / blog', 'Mixed format']} /><Textarea className="form-span-2" label="Audience description" value={data.audience} onChange={set('audience')} placeholder="Who are they, what do they care about, and why do they follow you?" /><Input label="Location" value={data.location} onChange={set('location')} placeholder="Ulaanbaatar, Mongolia" /><Select label="Primary language" value={data.language} onChange={set('language')} options={['Mongolian', 'English', 'Korean', 'Japanese', 'Chinese', 'Other']} /></div><StepActions current={current} onBack={() => setCurrent(0)} onNext={next} /></>}
    {current === 2 && <><StepHeading title="CONNECT YOUR" script="reach." copy="Linked accounts can earn verified status later. Manual links stay clearly marked as unverified." /><div className="form-grid"><Input label="Instagram" value={data.instagram} onChange={set('instagram')} placeholder="instagram.com/username" /><Input label="Facebook" value={data.facebook} onChange={set('facebook')} placeholder="facebook.com/page" /><Input className="form-span-2" label="Manual link" value={data.manualLink} onChange={set('manualLink')} placeholder="YouTube, TikTok, portfolio or other social URL" error={errors.social} /></div><div className="mt-6 grid gap-3 md:grid-cols-2"><Card className="flex gap-3"><CheckCircle2 className="shrink-0 text-[#2ca967]" size={20} /><div><Badge variant="mint">Verified</Badge><p className="mt-2 text-sm font-semibold">Connected account</p><p className="ui-help">Ownership and public audience metrics can be confirmed when API connection is added later.</p></div></Card><Card className="flex gap-3"><CircleAlert className="shrink-0 text-[#b87a12]" size={20} /><div><Badge variant="outline">Unverified</Badge><p className="mt-2 text-sm font-semibold">Manual profile link</p><p className="ui-help">Shown on your profile without a verification badge. No API is connected in this frontend demo.</p></div></Card></div><StepActions current={current} onBack={() => setCurrent(1)} onNext={next} /></>}
    {current === 3 && <><StepHeading title="SHOW THE" script="work." copy="Add one standout example. More portfolio pieces can be added after channel setup." /><div className="form-grid"><div className="form-span-2"><FileUpload label="Sample work" accept="image/*,video/*" value={data.sample} onChange={(files) => { const file = files[0] || null; setMediaFiles((value) => ({ ...value, sample: file })); setData((value) => ({ ...value, sample: file?.name || '' })) }} />{errors.sample && <p className="ui-error">{errors.sample}</p>}</div><Input label="Title" value={data.workTitle} onChange={set('workTitle')} placeholder="Summer city diary" error={errors.workTitle} /><Select label="Category" value={data.workCategory} onChange={set('workCategory')} options={['Brand campaign', 'UGC', 'Editorial', 'Review', 'Event coverage', 'Personal project']} /><Textarea className="form-span-2" label="Description" value={data.workDescription} onChange={set('workDescription')} placeholder="Briefly describe the concept, your role and the result." /></div><StepActions current={current} onBack={() => setCurrent(2)} onNext={next} /></>}
    {current === 4 && <><StepHeading title="SET YOUR" script="terms." copy="Give brands a starting point while staying in control of what the public can see." /><div className="form-grid"><Input label="Post rate" value={data.postRate} onChange={set('postRate')} placeholder="₮ 0" inputMode="numeric" /><Input label="Story rate" value={data.storyRate} onChange={set('storyRate')} placeholder="₮ 0" inputMode="numeric" /><Input label="Reel rate" value={data.reelRate} onChange={set('reelRate')} placeholder="₮ 0" inputMode="numeric" /><Select label="Availability" value={data.availability} onChange={set('availability')} options={['Available now', 'Available this month', 'Limited availability', 'Not accepting work']} error={errors.availability} /><Card className="form-span-2"><Switch label="Show rates publicly" description={data.publicRates ? 'Brands can see your starting prices.' : 'Rates are shared only after you approve an inquiry.'} checked={data.publicRates} onChange={set('publicRates')} /></Card></div><StepActions current={current} onBack={() => setCurrent(3)} onNext={next} /></>}
    {current === 5 && <><StepHeading title="READY TO" script="launch." copy="Review the essentials before creating your channel." /><div className="mb-6 flex items-center gap-3 rounded-2xl bg-mint-soft p-4 text-sm text-[#155b31]"><Sparkles size={18} /><strong>Your creator profile is ready for a final look.</strong></div><ReviewList items={[["Channel", data.channelName], ["Username", data.username], ["Niche", data.niche], ["Content format", data.format], ["Location", data.location], ["Social", data.instagram || data.facebook || data.manualLink], ["Portfolio", data.workTitle], ["Availability", data.availability], ["Rate visibility", data.publicRates ? 'Public' : 'Private']]} /><Card className="mt-5"><Checkbox label="I confirm this profile information is accurate" description="You can edit these fields later from My Account." checked={data.consent} onChange={set('consent')} /></Card><div className="mt-4 flex items-center gap-2 text-xs text-[var(--subtle)]"><LockKeyhole size={14} /> Profile data is sent securely to your account.</div><StepActions current={current} onBack={() => setCurrent(4)} onNext={finish} finish loading={finishing} /></>}
  </OnboardingLayout>
}
