import { useMemo, useState } from 'react'
import { ArrowLeft, Ban, BriefcaseBusiness, CheckCircle2, Eye, FileSignature, Flag, Gauge, ShieldCheck, Star, Users, UserRoundCheck } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { AdminDataPage, AdminHeader, AdminPage, AdminPanel, AdminStat, DangerAction, StatusBadge } from '../../components/admin/AdminUI'
import { Avatar, Badge, Button, Switch, useToast } from '../../components/ui'
import { adminCampaigns, adminChannels, adminContracts, adminUsers, auditLogs } from '../../data/admin'

const identity=(value)=><div className="flex items-center gap-3"><Avatar size="sm" fallback={value.slice(0,2).toUpperCase()}/><span><strong className="block text-xs">{value}</strong><small className="text-white/30">Verified platform record</small></span></div>
const detailRow=(label,value)=><div className="flex items-center justify-between gap-4 border-b border-white/[.07] py-3 text-xs"><span className="text-white/35">{label}</span><strong className="text-right">{value}</strong></div>

function ManagementTabs({active}){
  const navigate=useNavigate()
  const tabs=[['users','Users','/admin/users',Users],['channels','Channels','/admin/channels',UserRoundCheck],['creators','Creators','/admin/creators',Star],['businesses','Businesses','/admin/businesses',BriefcaseBusiness],['campaigns','Campaigns','/admin/campaigns',Gauge],['contracts','Contracts','/admin/contracts',FileSignature]]
  return <div className="mb-5 flex max-w-full gap-1 overflow-x-auto rounded-2xl border border-white/10 bg-[#151515] p-1.5 [scrollbar-width:none]">{tabs.map(([value,label,to,Icon])=><button ref={(node)=>{if(active===value)node?.scrollIntoView({block:'nearest',inline:'center'})}} type="button" key={value} onClick={()=>navigate(to)} className={`flex min-h-10 min-w-max flex-1 items-center justify-center gap-2 rounded-xl px-4 text-[11px] font-bold transition ${active===value?'bg-pink text-black':'text-white/40 hover:bg-white/[.05] hover:text-white'}`}><Icon size={14}/>{label}</button>)}</div>
}

export function AdminManagementPage({section='users'}){
  const navigate=useNavigate()
  const channelType=section==='creators'?'Creator':section==='businesses'?'Business':null

  if(section==='users'){
    return <AdminDataPage eyebrow="Management · Account directory" title="Management center" copy="Search, review and manage viewer accounts and their channel access." toolbar={<ManagementTabs active={section}/>} rows={adminUsers} getId={(row)=>row.id} onRow={(row)=>navigate(`/admin/users/${row.id}`)} columns={[
      {key:'name',label:'User',render:(row)=>identity(row.name)},{key:'email',label:'Email'},{key:'type',label:'Account type'},{key:'channels',label:'Channels'},{key:'status',label:'Status',render:(row)=><StatusBadge status={row.status}/>},{key:'joined',label:'Joined'},{key:'active',label:'Last active'},
    ]}/>
  }

  if(section==='channels'||channelType){
    const rows=channelType?adminChannels.filter((item)=>item.type===channelType):adminChannels
    return <AdminDataPage eyebrow="Management · Channel directory" title="Management center" copy={`Review ${channelType?channelType.toLowerCase():'creator and business'} identity, verification, visibility and trust status.`} toolbar={<ManagementTabs active={section}/>} rows={rows} getId={(row)=>row.id} onRow={(row)=>navigate(`/admin/channels/${row.id}`)} filters={['All','Active','Restricted','Suspended','Verified','Unverified']} columns={[
      {key:'name',label:'Channel',render:(row)=>identity(row.name)},{key:'type',label:'Type',render:(row)=><Badge variant={row.type==='Creator'?'pink':'mint'}>{row.type}</Badge>},{key:'owner',label:'Owner'},{key:'category',label:'Category'},{key:'followers',label:'Followers'},{key:'verified',label:'Verification',render:(row)=><StatusBadge status={row.verified}/>},{key:'status',label:'Status',render:(row)=><StatusBadge status={row.status}/>},{key:'reports',label:'Reports'},
    ]}/>
  }

  if(section==='campaigns'){
    return <AdminDataPage eyebrow="Management · Campaign governance" title="Management center" copy="Monitor campaign state, budget, creator participation and report signals." toolbar={<ManagementTabs active={section}/>} rows={adminCampaigns} getId={(row)=>row.id} onRow={(row)=>navigate(`/admin/campaigns/${row.id}`)} filters={['All','Open','In progress','Draft','Paused']} columns={[
      {key:'title',label:'Campaign'},{key:'business',label:'Business'},{key:'status',label:'Status',render:(row)=><StatusBadge status={row.status}/>},{key:'budget',label:'Budget'},{key:'applications',label:'Applications'},{key:'creators',label:'Creators'},{key:'deadline',label:'Deadline'},{key:'reports',label:'Reports'},
    ]}/>
  }

  return <AdminDataPage eyebrow="Management · Agreement oversight" title="Management center" copy="Review parties, milestones, escrow status and disputes across active agreements." toolbar={<ManagementTabs active="contracts"/>} rows={adminContracts} getId={(row)=>row.id} onRow={(row)=>navigate(`/admin/contracts/${row.id}`)} filters={['All','In progress','Completed','Disputed','Payment required']} columns={[
    {key:'id',label:'Contract'},{key:'campaign',label:'Campaign'},{key:'creator',label:'Creator'},{key:'business',label:'Business'},{key:'amount',label:'Value'},{key:'status',label:'Status',render:(row)=><StatusBadge status={row.status}/>},{key:'payment',label:'Payment'},{key:'deadline',label:'Deadline'},
  ]}/>
}

export function AdminUsersPage(){const navigate=useNavigate();return <AdminDataPage eyebrow="Management · Account directory" title="Management center" copy="Search, review and manage viewer accounts and their channel access." toolbar={<ManagementTabs active="users"/>} rows={adminUsers} getId={(row)=>row.id} onRow={(row)=>navigate(`/admin/users/${row.id}`)} columns={[
  {key:'name',label:'User',render:(row)=>identity(row.name)},{key:'email',label:'Email'},{key:'type',label:'Account type'},{key:'channels',label:'Channels'},{key:'status',label:'Status',render:(row)=><StatusBadge status={row.status}/>},{key:'joined',label:'Joined'},{key:'active',label:'Last active'},
]}/>}

export function AdminUserDetailPage(){const {userId}=useParams();const navigate=useNavigate();const user=adminUsers.find((item)=>item.id===userId)||adminUsers[0];return <AdminPage><button onClick={()=>navigate('/admin/users')} className="mb-5 flex items-center gap-2 text-xs text-white/40 hover:text-white"><ArrowLeft size={14}/>Back to users</button><AdminHeader eyebrow={`User record · ${user.id}`} title={user.name} copy={`${user.email} · Joined ${user.joined}`} date={false} action={<div className="flex gap-2"><Button variant="outline"><Eye size={14}/>Impersonation preview</Button><DangerAction label="Suspend user" description={`Suspend ${user.name} and restrict access to every connected channel?`}/></div>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminStat label="Account status" value={user.status} change="Risk score · Low" tone="mint"/><AdminStat label="Connected channels" value={String(user.channels)} change={user.type}/><AdminStat label="Lifetime spend" value="₮18.4M" change="Across 8 contracts"/><AdminStat label="Reports" value="1" change="No active escalation"/></div><div className="mt-5 grid gap-5 xl:grid-cols-3"><AdminPanel title="Account information">{detailRow('Email',user.email)}{detailRow('Account type',user.type)}{detailRow('Last active',user.active)}{detailRow('Location','Ulaanbaatar, Mongolia')}{detailRow('Language','Mongolian · English')}</AdminPanel><AdminPanel title="Channels"><div className="rounded-xl border border-white/10 p-4">{identity(user.name)}<div className="mt-4 flex justify-between"><Badge variant="pink">{user.type.includes('Business')?'Business':'Creator'}</Badge><StatusBadge status={user.status}/></div></div></AdminPanel><AdminPanel title="Account controls"><div className="space-y-5"><Switch label="Email verified" description="Read-only preview · primary email ownership confirmed." checked disabled/><Switch label="Login access" description="Read-only preview · use Suspend user to change access." checked={user.status==='Active'} disabled/><Switch label="Featured eligibility" description="Read-only until moderation API is connected." checked disabled/></div></AdminPanel></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><AdminPanel title="Marketplace history"><div className="grid grid-cols-2 gap-3">{[['Campaigns','8'],['Contracts','12'],['Payments','₮18.4M'],['Reviews','4.9 / 5']].map(([label,value])=><div className="rounded-xl border border-white/10 p-4" key={label}><small className="text-white/30">{label}</small><b className="mt-2 block text-lg">{value}</b></div>)}</div></AdminPanel><AdminPanel title="Recent audit activity">{auditLogs.slice(0,3).map((log)=><div key={log.id} className="flex justify-between border-b border-white/[.07] py-3 text-xs"><span><b className="block">{log.action}</b><small className="text-white/30">{log.actor}</small></span><time className="text-white/25">{log.time}</time></div>)}</AdminPanel></div></AdminPage>}

export function AdminChannelsPage({type}){const navigate=useNavigate();const rows=useMemo(()=>type?adminChannels.filter((item)=>item.type===type):adminChannels,[type]);const active=type==='Creator'?'creators':type==='Business'?'businesses':'channels';return <AdminDataPage eyebrow="Management · Channel directory" title="Management center" copy={`Review ${type?type.toLowerCase():'creator and business'} identity, verification, visibility and trust status.`} toolbar={<ManagementTabs active={active}/>} rows={rows} getId={(row)=>row.id} onRow={(row)=>navigate(`/admin/channels/${row.id}`)} filters={['All','Active','Restricted','Suspended','Verified','Unverified']} columns={[
  {key:'name',label:'Channel',render:(row)=>identity(row.name)},{key:'type',label:'Type',render:(row)=><Badge variant={row.type==='Creator'?'pink':'mint'}>{row.type}</Badge>},{key:'owner',label:'Owner'},{key:'category',label:'Category'},{key:'followers',label:'Followers'},{key:'verified',label:'Verification',render:(row)=><StatusBadge status={row.verified}/>},{key:'status',label:'Status',render:(row)=><StatusBadge status={row.status}/>},{key:'reports',label:'Reports'},
]}/>}

export function AdminChannelDetailPage(){const {channelId}=useParams();const navigate=useNavigate();const {toast}=useToast();const channel=adminChannels.find((item)=>item.id===channelId)||adminChannels[0];const [featured,setFeatured]=useState(channel.featured);return <AdminPage><button onClick={()=>navigate('/admin/channels')} className="mb-5 flex items-center gap-2 text-xs text-white/40 hover:text-white"><ArrowLeft size={14}/>Back to channels</button><AdminHeader eyebrow={`${channel.type} channel · ${channel.id}`} title={channel.name} copy={`${channel.category} · Owned by ${channel.owner}`} date={false} action={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>toast('Verification approved.',{type:'success'})}><ShieldCheck size={14}/>Verify</Button><DangerAction label="Restrict" description={`Restrict publishing and marketplace actions for ${channel.name}?`}/></div>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminStat label="Followers" value={channel.followers} change="+8.4% in 30 days" tone="mint"/><AdminStat label="Rating" value="4.9" change="128 verified reviews"/><AdminStat label="Active campaigns" value={channel.type==='Business'?'6':'3'} change="No overdue items"/><AdminStat label="Reports" value={String(channel.reports)} change={channel.reports?'Requires attention':'Clean record'} tone={channel.reports?'danger':'mint'}/></div><div className="mt-5 grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><AdminPanel title="Identity & visibility">{detailRow('Channel type',channel.type)}{detailRow('Owner',channel.owner)}{detailRow('Category',channel.category)}{detailRow('Verification',channel.verified)}{detailRow('Status',channel.status)}<div className="mt-5"><Switch label="Featured channel" description="Show in editorial and discovery placements." checked={featured} onChange={()=>setFeatured(!featured)}/></div></AdminPanel><AdminPanel title="Performance overview"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Profile views','48.2K'],['Saves','3,842'],['Follows','2,418'],['Conversion','6.8%']].map(([label,value])=><div key={label} className="rounded-xl border border-white/10 p-4"><small className="text-white/30">{label}</small><b className="mt-2 block text-lg">{value}</b></div>)}</div><div className="mt-5 rounded-xl border border-white/10 p-4 text-xs leading-6 text-white/45">The channel has a healthy marketplace history, consistent response time and complete public identity information.</div></AdminPanel></div><AdminPanel className="mt-5" title="Administrative actions"><div className="flex flex-wrap gap-2"><Button variant="outline"><Star size={14}/>Feature channel</Button><Button variant="outline"><UserRoundCheck size={14}/>Change owner</Button><Button variant="outline"><Flag size={14}/>Open reports</Button><DangerAction label="Suspend channel"/><DangerAction label="Delete channel" title="Delete channel record"/></div></AdminPanel></AdminPage>}

export function AdminCampaignsPage(){const navigate=useNavigate();return <AdminDataPage eyebrow="Management · Campaign governance" title="Management center" copy="Monitor campaign state, budget, creator participation and report signals." toolbar={<ManagementTabs active="campaigns"/>} rows={adminCampaigns} getId={(row)=>row.id} onRow={(row)=>navigate(`/admin/campaigns/${row.id}`)} filters={['All','Open','In progress','Draft','Paused']} columns={[
  {key:'title',label:'Campaign'},{key:'business',label:'Business'},{key:'status',label:'Status',render:(row)=><StatusBadge status={row.status}/>},{key:'budget',label:'Budget'},{key:'applications',label:'Applications'},{key:'creators',label:'Creators'},{key:'deadline',label:'Deadline'},{key:'reports',label:'Reports'},
]}/>}

export function AdminCampaignDetailPage(){const {campaignId}=useParams();const navigate=useNavigate();const item=adminCampaigns.find((row)=>row.id===campaignId)||adminCampaigns[0];return <AdminPage><button onClick={()=>navigate('/admin/campaigns')} className="mb-5 flex items-center gap-2 text-xs text-white/40"><ArrowLeft size={14}/>Back to campaigns</button><AdminHeader eyebrow={`Campaign · ${item.id}`} title={item.title} copy={`${item.business} · Created ${item.created}`} date={false} action={<div className="flex gap-2"><Button variant="outline"><CheckCircle2 size={14}/>Approve</Button><DangerAction label="Pause campaign"/></div>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminStat label="Budget" value={item.budget} change="Budget disclosure verified"/><AdminStat label="Applications" value={String(item.applications)} change="12 shortlisted" tone="mint"/><AdminStat label="Hired creators" value={String(item.creators)} change="Across 3 deliverables"/><AdminStat label="Reports" value={String(item.reports)} change={item.reports?'Open report exists':'No active reports'} tone={item.reports?'danger':'mint'}/></div><div className="mt-5 grid gap-5 xl:grid-cols-3"><AdminPanel title="Campaign information">{detailRow('Business',item.business)}{detailRow('Status',item.status)}{detailRow('Deadline',item.deadline)}{detailRow('Mode','Open application')}{detailRow('Platform','Instagram · TikTok')}</AdminPanel><AdminPanel title="Deliverables"><div className="space-y-3">{['1 editorial reel','3 story frames','30-day content usage'].map((text,index)=><div key={text} className="flex gap-3 rounded-xl border border-white/10 p-3 text-xs"><span className="grid size-6 place-items-center rounded-full bg-pink text-black">{index+1}</span>{text}</div>)}</div></AdminPanel><AdminPanel title="Admin controls"><div className="space-y-4"><Switch label="Discovery visibility" description="Read-only preview" checked disabled/><Switch label="Accept applications" description="Read-only preview" checked={item.status==='Open'} disabled/><Switch label="Featured placement" description="Unavailable until moderation API is connected." checked={false} disabled/><DangerAction label="Cancel campaign"/></div></AdminPanel></div></AdminPage>}

export function AdminContractsPage(){const navigate=useNavigate();return <AdminDataPage eyebrow="Management · Agreement oversight" title="Management center" copy="Review parties, milestones, escrow status and disputes across active agreements." toolbar={<ManagementTabs active="contracts"/>} rows={adminContracts} getId={(row)=>row.id} onRow={(row)=>navigate(`/admin/contracts/${row.id}`)} filters={['All','In progress','Completed','Disputed','Payment required']} columns={[
  {key:'id',label:'Contract'},{key:'campaign',label:'Campaign'},{key:'creator',label:'Creator'},{key:'business',label:'Business'},{key:'amount',label:'Value'},{key:'status',label:'Status',render:(row)=><StatusBadge status={row.status}/>},{key:'payment',label:'Payment'},{key:'deadline',label:'Deadline'},
]}/>}

export function AdminContractDetailPage(){const {contractId}=useParams();const navigate=useNavigate();const item=adminContracts.find((row)=>row.id===contractId)||adminContracts[0];return <AdminPage><button onClick={()=>navigate('/admin/contracts')} className="mb-5 flex items-center gap-2 text-xs text-white/40"><ArrowLeft size={14}/>Back to contracts</button><AdminHeader eyebrow="Contract oversight" title={item.id} copy={`${item.campaign} · ${item.creator} × ${item.business}`} date={false} action={<DangerAction label="Freeze contract" icon={Ban}/>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminStat label="Contract value" value={item.amount} change="10% platform commission"/><AdminStat label="Contract status" value={item.status} change={`Deadline ${item.deadline}`}/><AdminStat label="Payment state" value={item.payment} change="Mock escrow record" tone="mint"/><AdminStat label="Dispute" value={item.dispute} change="Administrative review"/></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><AdminPanel title="Agreement summary">{detailRow('Creator',item.creator)}{detailRow('Business',item.business)}{detailRow('Campaign',item.campaign)}{detailRow('Signed','Jul 14, 2026')}{detailRow('Usage rights','90 days · Digital')}</AdminPanel><AdminPanel title="Milestones">{[['Concept approval','Completed'],['Content production','In progress'],['Final delivery','Pending'],['Payment release','Pending']].map(([label,status])=><div key={label} className="flex items-center justify-between border-b border-white/[.07] py-3 text-xs"><span>{label}</span><StatusBadge status={status}/></div>)}</AdminPanel></div><AdminPanel className="mt-5" title="Administrative actions"><div className="flex flex-wrap gap-2"><Button variant="outline">View payment ledger</Button><Button variant="outline">Open conversation</Button><DangerAction label="Freeze payment"/><DangerAction label="Terminate contract"/></div></AdminPanel></AdminPage>}
