import { useState } from 'react'
import { ArrowLeft, Check, Eye, Flag, ShieldCheck, X } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { AdminDataPage, AdminHeader, AdminPage, AdminPanel, AdminStat, DangerAction, StatusBadge } from '../../components/admin/AdminUI'
import { Badge, Button, Drawer, Textarea, useToast } from '../../components/ui'
import { adminDisputes, adminReports, moderationItems, verifications } from '../../data/admin'

export function AdminDisputesPage(){const navigate=useNavigate();return <AdminDataPage eyebrow="Trust & safety · Resolution queue" title="Disputes" copy="Review contract disagreements, evidence and pending resolution work." rows={adminDisputes} getId={(row)=>row.id} onRow={(row)=>navigate(`/admin/disputes/${row.id}`)} filters={['All','Under Review','Waiting for Business','Waiting for Creator','Urgent']} columns={[
  {key:'id',label:'Dispute'},{key:'contract',label:'Contract'},{key:'creator',label:'Creator'},{key:'business',label:'Business'},{key:'reason',label:'Reason'},{key:'priority',label:'Priority',render:(row)=><Badge variant={row.priority==='Urgent'?'pink':'outline'}>{row.priority}</Badge>},{key:'status',label:'Status',render:(row)=><StatusBadge status={row.status}/>},{key:'opened',label:'Opened'},
]}/>}

export function AdminDisputeDetailPage(){const {disputeId}=useParams();const navigate=useNavigate();const {toast}=useToast();const item=adminDisputes.find((row)=>row.id===disputeId)||adminDisputes[0];return <AdminPage><button onClick={()=>navigate('/admin/disputes')} className="mb-5 flex items-center gap-2 text-xs text-white/40"><ArrowLeft size={14}/>Back to disputes</button><AdminHeader eyebrow={`Dispute · ${item.id}`} title={item.reason} copy={`${item.creator} × ${item.business} · Opened ${item.opened}`} date={false} action={<DangerAction label="Close dispute" variant="pink"/>}/><div className="grid gap-4 sm:grid-cols-3"><AdminStat label="Priority" value={item.priority} change="Resolution SLA · 24h" tone="danger"/><AdminStat label="Status" value={item.status} change="Assigned to Bolor Admin"/><AdminStat label="Contract" value={item.contract} change="Payment currently frozen"/></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><AdminPanel title="Party statements"><div className="space-y-3">{[[item.creator,'The final request differs from the signed deliverable scope.'],[item.business,'The revision falls within the agreed creative direction.']].map(([name,copy])=><div key={name} className="rounded-xl border border-white/10 p-4"><b className="text-xs">{name}</b><p className="mt-2 text-xs leading-5 text-white/45">{copy}</p></div>)}</div></AdminPanel><AdminPanel title="Evidence & timeline">{['Original creative brief.pdf','Revision request · Jul 19','Creator response · Jul 20','Business escalation · Jul 21'].map((entry)=><button key={entry} className="flex w-full items-center justify-between border-b border-white/[.07] py-3 text-left text-xs"><span>{entry}</span><Eye size={14} className="text-white/30"/></button>)}</AdminPanel></div><AdminPanel className="mt-5" title="Internal resolution note"><Textarea rows={4} placeholder="Record a private admin note..."/><div className="mt-4 flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={()=>toast('More evidence requested.')}>Request evidence</Button><Button variant="outline" onClick={()=>toast('Decision recorded for business.')}>Resolve for business</Button><Button variant="pink" onClick={()=>toast('Decision recorded for creator.',{type:'success'})}>Resolve for creator</Button></div></AdminPanel></AdminPage>}

export function AdminReportsPage(){const {toast}=useToast();return <AdminDataPage eyebrow="Trust & safety · User reports" title="Reports" copy="Triage reported channels, campaigns and content with clear priority signals." rows={adminReports} getId={(row)=>row.id} filters={['All','Pending','Reviewing','Escalated','Urgent']} columns={[
  {key:'id',label:'Report'},{key:'target',label:'Target'},{key:'targetType',label:'Type'},{key:'reason',label:'Reason'},{key:'reporter',label:'Reporter'},{key:'priority',label:'Priority',render:(row)=><Badge variant={row.priority==='Urgent'?'pink':'outline'}>{row.priority}</Badge>},{key:'status',label:'Status',render:(row)=><StatusBadge status={row.status}/>},{key:'created',label:'Created'},
]} actions={<Button variant="pink" onClick={()=>toast('Oldest high-priority report opened.')}>Review next</Button>}/>}

export function AdminModerationPage(){const {toast}=useToast();return <AdminPage><AdminHeader eyebrow="Trust & safety · Visual review" title="Content moderation" copy="Review reported campaign media without leaving the admin workspace."/><div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{moderationItems.map((item)=><article key={item.id} className="group overflow-hidden rounded-[1.25rem] border border-white/10 bg-[#151515] transition hover:-translate-y-0.5 hover:border-white/20"><div className="relative aspect-[16/9] overflow-hidden"><img src={item.image} alt="" loading="lazy" decoding="async" className="size-full object-cover transition duration-500 group-hover:scale-[1.025]"/><div className="absolute inset-x-0 top-0 flex items-start justify-between gap-2 bg-gradient-to-b from-black/70 to-transparent p-3"><StatusBadge status={item.status}/><Badge variant="pink">{item.reports} reports</Badge></div></div><div className="p-4"><h2 className="line-clamp-2 text-sm font-bold leading-5">{item.caption}</h2><p className="mt-1.5 truncate text-[11px] text-white/35">{item.creator} × {item.business}</p><div className="mt-4 grid grid-cols-2 gap-2 border-t border-white/[.07] pt-3"><Button size="sm" variant="mint" onClick={()=>toast('Content approved locally.',{type:'success'})}><Check size={13}/>Approve</Button><Button size="sm" variant="outline" onClick={()=>toast('Content hidden locally.',{type:'info'})}><X size={13}/>Hide</Button><DangerAction className="col-span-2 w-full" size="sm" label="Remove content"/></div></div></article>)}</div></AdminPage>}

export function AdminVerificationsPage(){const [selected,setSelected]=useState(null);const {toast}=useToast();return <><AdminDataPage eyebrow="Trust & safety · Identity checks" title="Verifications" copy="Review creator, business, payer and linked social account verification requests." rows={verifications} getId={(row)=>row.id} onRow={setSelected} filters={['All','Pending','Reviewing','Approved','Low','Medium']} columns={[
  {key:'name',label:'Applicant'},{key:'type',label:'Verification type'},{key:'submitted',label:'Submitted'},{key:'risk',label:'Risk',render:(row)=><Badge variant={row.risk==='Low'?'mint':'pink'}>{row.risk}</Badge>},{key:'history',label:'History'},{key:'status',label:'Status',render:(row)=><StatusBadge status={row.status}/>},
]}/><Drawer open={Boolean(selected)} onClose={()=>setSelected(null)} title="Verification review">{selected&&<div><div className="rounded-2xl border border-white/10 p-5"><ShieldCheck className="text-mint"/><h3 className="mt-4 text-xl font-bold">{selected.name}</h3><p className="mt-1 text-xs text-white/35">{selected.type} · {selected.id}</p></div><div className="my-5 space-y-3">{['Government ID','Ownership / authorization document','Social account proof'].map((item)=><button key={item} className="flex w-full justify-between rounded-xl border border-white/10 p-4 text-xs">{item}<Eye size={14}/></button>)}</div><div className="flex gap-2"><Button variant="outline" onClick={()=>toast('Verification rejected.')}>Reject</Button><Button variant="pink" onClick={()=>toast('Verification approved.',{type:'success'})}>Approve verification</Button></div></div>}</Drawer></>}

export function AdminReviewsPage(){const reviews=[{id:'rev-21',author:'GOBI Cashmere',target:'Amara Bat',rating:'5.0',text:'Excellent creative direction and reliable delivery.',status:'Published',date:'Jul 22'},{id:'rev-19',author:'Playtime Festival',target:'Mika Play',rating:'2.0',text:'Scope and revision expectations were unclear.',status:'Reported',date:'Jul 20'},{id:'rev-14',author:'Aero Mongolia',target:'Temuulen Film',rating:'4.8',text:'Beautiful final film and thoughtful storytelling.',status:'Published',date:'Jul 18'}];return <AdminDataPage eyebrow="Trust & safety · Reputation" title="Reviews" copy="Monitor marketplace feedback and moderate reported reviews." rows={reviews} getId={(row)=>row.id} filters={['All','Published','Reported']} columns={[
  {key:'author',label:'Author'},{key:'target',label:'Target'},{key:'rating',label:'Rating'},{key:'text',label:'Review'},{key:'status',label:'Status',render:(row)=><StatusBadge status={row.status}/>},{key:'date',label:'Date'},
]} actions={<Button variant="outline"><Flag size={14}/>Reported only</Button>}/>}
