import { Router } from 'express';
import { validate } from '../../shared/middleware/validate.js';
import { authenticate } from '../auth/public.js';
import { reviewController } from './review.controller.js';
import { declineShowcaseSchema, proofListSchema, reviewListSchema, showcaseConsentSchema, submitProofSchema, submitReviewSchema } from './review.schema.js';
export const collaborationReviewRouter = Router();
collaborationReviewRouter.use(authenticate);
collaborationReviewRouter.get('/:id/reviews', validate(reviewListSchema), reviewController.list);
collaborationReviewRouter.post('/:id/reviews', validate(submitReviewSchema), reviewController.submit);
collaborationReviewRouter.post('/:id/showcase', validate(showcaseConsentSchema), reviewController.giveShowcaseConsent);
collaborationReviewRouter.post('/:id/showcase/decline', validate(declineShowcaseSchema), reviewController.declineShowcaseConsent);
collaborationReviewRouter.get('/:id/proofs', validate(proofListSchema), reviewController.proofs);
collaborationReviewRouter.post('/:id/proofs', validate(submitProofSchema), reviewController.submitProof);
